import fs from 'node:fs';
import {projects} from './projects.mjs';
const read=name=>JSON.parse(fs.readFileSync(new URL(name,import.meta.url),'utf8').replace(/^\uFEFF/,''));
const inventory=read('inventory.json'),screenshots=read('screenshots.json');
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const categories=['Scuola','Creatività','Produttività','Benessere','Sport','Business','Esperienze'];
const date=s=>new Date(s+'T12:00:00').toLocaleDateString('it-IT',{day:'numeric',month:'short',year:'numeric'});
const data=projects.map((p,i)=>{const repo=inventory.find(x=>x.folder===p.folder);return {...p,index:i,...repo,repo:repo?.repo?.replace(/\.git$/,'')||null,url:p.url||repo?.homepage||null,last:repo?.last,shot:screenshots.find(x=>x.folder===p.folder&&x.image)};});
const cards=data.map(p=>`<article class="project" data-category="${p.category}" data-name="${esc(p.name)}" data-date="${p.last}" data-search="${esc([p.name,p.category,p.type,p.description,...p.features].join(' ').toLocaleLowerCase('it'))}" id="${p.mark.toLowerCase().replace('@','at')}">
<div class="exhibit-heading"><span class="exhibit-number">${String(p.index+1).padStart(2,'0')}</span><span>${p.category}</span><span class="type">${p.type}</span></div>
${p.shot?`<a class="screenshot-link" href="${p.shot.image}" data-screenshot="${p.shot.image}" data-title="${esc(p.name)}" data-caption="${['FILO','professAI','schoolify'].includes(p.folder)?'Schermata di accesso':'Pagina pubblica'} · 3 ottobre 2026" aria-label="Ingrandisci screenshot di ${esc(p.name)}"><img src="${p.shot.image}" alt="${esc(p.name)}: screenshot della pagina pubblica" width="1365" height="900" loading="lazy"><span class="zoom-icon" aria-hidden="true">+</span><span class="screenshot-caption">ESPLORA L’INTERFACCIA</span></a>`:`<div class="screenshot-missing"><span>reCoding<span class="os-outline">OS</span></span><small>SISTEMA OPERATIVO / NESSUNA ANTEPRIMA</small></div>`}
<div class="exhibit-copy"><h3>${p.name}</h3><p class="tagline">${p.tagline}</p><p class="description">${p.description}</p><ul>${p.features.map(f=>`<li>${f}</li>`).join('')}</ul><div class="card-links">${p.url?`<a class="visit" href="${p.url}" target="_blank" rel="noopener noreferrer">Apri il progetto <span aria-hidden="true">↗</span></a>`:'<span class="no-site">Sito non documentato</span>'}<a class="repo" href="${p.repo}" target="_blank" rel="noopener noreferrer" aria-label="Repository GitHub di ${esc(p.name)}">GitHub${p.private?' · privato':''}</a></div><div class="card-date">Ultimo commit · ${date(p.last)}</div></div></article>`).join('\n');
const html=`<!doctype html><html lang="it"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>SHOWROOM — Mediaera Srl</title><meta name="description" content="21 progetti. Sette mondi. Esplora le applicazioni promosse da Mediaera Srl, con descrizioni, caratteristiche e screenshot."><meta name="theme-color" content="#141414"><link rel="icon" type="image/svg+xml" href="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 40 40'%3E%3Crect width='40' height='40' fill='%23ff663b'/%3E%3Ctext x='20' y='29' text-anchor='middle' font-size='30' font-family='sans-serif' font-weight='bold' fill='%23141414'%3Em%3C/text%3E%3C/svg%3E"><link rel="stylesheet" href="style.css"><script src="app.js" defer></script></head>
<body><a class="skip" href="#catalogo">Vai ai progetti</a><header class="site-header"><a class="brand" href="#" aria-label="Mediaera Srl, inizio"><span class="brand-mark" aria-hidden="true">m<span>↗</span></span><span>MEDIAERA<small>SRL / DIGITAL MAKERS</small></span></a><div class="header-edition">RACCOLTA 2026 <span>VOL. 01</span></div><nav aria-label="Navigazione principale"><a href="#catalogo">Esplora <sup>21</sup></a><a href="#raccolta">Il progetto</a></nav></header>
<main><section class="hero" aria-labelledby="hero-title"><div class="hero-kicker"><span>UN’ESPOSIZIONE DI IDEE CHE FUNZIONANO.</span><span>20.05 — 03.10 / 2026</span></div><h1 id="hero-title">SHOW<span>ROOM</span><i aria-hidden="true">/01</i></h1><div class="hero-floor"><div class="hero-manifesto"><span class="tiny-label">SOFTWARE BY PEOPLE.</span><h2>21 progetti.<br>Sette mondi.<br><em>Una firma.</em></h2><p>Dalla scuola alla creatività, dal lavoro allo sport. Le applicazioni promosse da Mediaera Srl, tutte da esplorare.</p><a class="primary" href="#catalogo">Entra nello showroom <span aria-hidden="true">↓</span></a></div><div class="hero-installation"><a class="hero-image rear left" href="#lo"><img src="assets/screenshots/lo.jpg" alt="LocAIndina, studio creativo per locandine" width="1365" height="900"><span>12 / LOCAINDINA</span></a><a class="hero-image rear right" href="#vu"><img src="assets/screenshots/vu.jpg" alt="VidMeUp, immagini e mini video" width="1365" height="900"><span>20 / VIDMEUP</span></a><a class="hero-image front" href="#rc"><img src="assets/recoding.webp" alt="Il desktop reCoding con strumenti STEM" width="1200" height="750"><span><b>01</b> RECODING <i>IL LABORATORIO NEL BROWSER</i></span></a><span class="installation-index">SELEZIONE DALLA COLLEZIONE / 2026</span></div></div></section>
<div class="collection-band" aria-label="Ambiti della raccolta"><span>SCUOLA</span><b>✳</b><span>CREATIVITÀ</span><b>✳</b><span>PRODUTTIVITÀ</span><b>✳</b><span>BENESSERE</span><b>✳</b><span>SPORT</span><b>✳</b><span>BUSINESS</span><b>✳</b><span>ESPERIENZE</span></div>
<section class="catalogue" id="catalogo"><div class="section-head"><div><div class="tiny-label">L’ESPOSIZIONE COMPLETA</div><h2>SCEGLI COSA<br><span>ESPLORARE.</span></h2></div><div class="collection-total"><strong>21</strong><span>APPLICAZIONI<br>DA SCOPRIRE</span></div></div><div class="catalogue-toolbar"><div class="controls" hidden><div class="search-wrap"><span aria-hidden="true">⌕</span><input type="search" id="search" placeholder="Cerca un progetto o un’idea" aria-label="Cerca nei progetti"><kbd aria-hidden="true">/</kbd></div><label class="sort-label">Ordina per<select id="sort"><option value="curated">In esposizione</option><option value="recent">Attività più recente</option><option value="name">Nome A–Z</option></select></label></div><div class="filter-row"><div class="filters" aria-label="Filtra per ambito" hidden><button class="filter active" data-filter="Tutti" aria-pressed="true">Tutti <span>21</span></button>${categories.map(c=>`<button class="filter" data-filter="${c}" aria-pressed="false">${c} <span>${data.filter(p=>p.category===c).length}</span></button>`).join('')}</div><span id="result-count" class="result-count" role="status" aria-live="polite">21 progetti</span></div></div><div class="project-grid">${cards}</div><div class="empty" hidden><h3>NESSUNA CORRISPONDENZA.</h3><p>Prova un’altra parola o torna alla collezione completa.</p><button id="reset">Mostra tutti i progetti</button></div><noscript><p>Il catalogo completo è disponibile anche senza JavaScript. Attivalo per ricerca e filtri.</p></noscript></section>
<section class="about" id="raccolta"><div class="about-title"><span class="tiny-label">LA FIRMA DIETRO LE IDEE</span><h2>MEDIAERA<span>SRL.</span></h2></div><div class="about-copy"><p class="about-intro">Il software è un modo<br>di mettere le idee al lavoro.</p><p>Ventuno progetti, con esigenze e pubblici diversi. Mediaera Srl promuove questa raccolta di strumenti per imparare, creare e affrontare le attività di ogni giorno.</p><p class="credits"><span>PROMOTRICE <b>Mediaera Srl</b></span><span>SVILUPPO <b>Andrea Battellocchi</b></span></p><details><summary>Note sulla collezione e sulle immagini</summary><p>Raccolta verificata il 3 ottobre 2026 sui repository GitHub e sulla documentazione dei prodotti. Le date indicano attività nel periodo 20 maggio–3 ottobre 2026, non necessariamente il lancio. Alcuni repository richiedono accesso autorizzato.</p><p>20 screenshot reali da pagine pubbliche, incluse schermate di accesso. Le presentazioni delle app Android non sono screenshot delle app installate. I siti promozionali sono accorpati ai rispettivi prodotti.</p></details><a class="text-link" href="https://github.com/yellowelise/showroom" target="_blank" rel="noopener noreferrer">Il progetto su GitHub ↗</a></div></section></main><footer><span>MEDIAERA SRL © 2026</span><span>IDEATO. SVILUPPATO. IN MOSTRA.</span><a href="#">Torna all’inizio ↑</a></footer><dialog id="screenshot-dialog" aria-labelledby="screenshot-title"><div class="dialog-header"><div><h2 id="screenshot-title"></h2><p id="screenshot-caption"></p></div><button id="close-screenshot" type="button" aria-label="Chiudi screenshot">Chiudi ×</button></div><img id="screenshot-full" alt=""></dialog></body></html>`;
fs.writeFileSync(new URL('dist/index.html',import.meta.url),html);
console.log(`Generated exhibition: ${data.length} projects.`);
