import fs from 'node:fs';
import {projects} from './projects.mjs';
const inventory=JSON.parse(fs.readFileSync(new URL('inventory.json',import.meta.url),'utf8').replace(/^\uFEFF/,'')).filter(row=>projects.some(project=>project.folder===row.folder));
const screenshots=JSON.parse(fs.readFileSync(new URL('screenshots.json',import.meta.url),'utf8')).filter(row=>projects.some(project=>project.folder===row.folder));
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const categories=['Scuola','Creatività','Produttività','Benessere','Sport','Business','Esperienze'];
const date=s=>new Date(s+'T12:00:00').toLocaleDateString('it-IT',{day:'numeric',month:'short',year:'numeric'});
const data=projects.map((p,i)=>{const repo=inventory.find(x=>x.folder===p.folder);const shot=screenshots.find(x=>x.folder===p.folder&&x.image);return {...p,index:i,...repo,repo:repo?.repo?.replace(/\.git$/,'')||null,url:p.url||repo?.homepage||null,last:repo?.last||'2026-09-27',shot};});
const cards=data.map(p=>`<article class="project" data-category="${p.category}" data-name="${esc(p.name)}" data-date="${p.last}" data-search="${esc([p.name,p.category,p.type,p.description,...p.features].join(' ').toLocaleLowerCase('it'))}" id="${p.mark.toLowerCase().replace('@','at')}">
${p.shot?`<a class="screenshot-link" href="${p.shot.image}" data-screenshot="${p.shot.image}" data-title="${esc(p.name)}" data-caption="${['FILO','professAI','schoolify'].includes(p.folder)?'Schermata di accesso':'Pagina pubblica'} · 3 ottobre 2026" aria-label="Ingrandisci screenshot di ${esc(p.name)}"><img src="${p.shot.image}" alt="${esc(p.name)}: screenshot della pagina pubblica" width="1365" height="900" loading="lazy"><span>Ingrandisci screenshot</span></a>`:'<div class="screenshot-missing">'+(p.repo?'Anteprima non disponibile':'Prototipo locale')+'</div>'}
<div class="card-top"><span class="app-mark c${categories.indexOf(p.category)}" aria-hidden="true">${p.mark}</span><span class="type">${p.type}</span></div>
<div class="category">${p.category}</div><h3>${p.name}</h3><p class="tagline">${p.tagline}</p><p class="description">${p.description}</p>
<ul>${p.features.map(f=>`<li>${f}</li>`).join('')}</ul>
<div class="card-links">${p.url?`<a class="visit" href="${p.url}" target="_blank" rel="noopener noreferrer">Visita il sito</a>`:'<span class="no-site">Sito non documentato</span>'}${p.repo?`<a class="repo" href="${p.repo}" target="_blank" rel="noopener noreferrer" aria-label="Repository GitHub di ${esc(p.name)}">GitHub${p.private?' · privato':''}</a>`:'<span class="no-site">Repository non online</span>'}</div>
<div class="card-date">${p.verifiedRemote?'Ultimo commit GitHub':'Snapshot documentato'} · ${date(p.last)}</div></article>`).join('\n');
const html=`<!doctype html><html lang="it"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Mediaera Srl — App Showroom</title><meta name="description" content="Esplora ${data.length} app, web app e progetti promossi da Mediaera Srl: scuola, creatività, produttività, benessere e sport. Maggio–ottobre 2026."><meta name="theme-color" content="#112c27"><link rel="icon" type="image/svg+xml" href="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 40 40'%3E%3Crect width='40' height='40' rx='10' fill='%23112c27'/%3E%3Ctext x='20' y='28' text-anchor='middle' font-size='27' font-family='Georgia' fill='%23dcff88'%3Em.%3C/text%3E%3C/svg%3E"><link rel="stylesheet" href="style.css"><script src="app.js" defer></script></head>
<body><a class="skip" href="#catalogo">Vai ai progetti</a><header class="site-header"><a class="brand" href="#"><span class="brand-symbol">m.</span><span>Mediaera Srl<small>APP SHOWROOM</small></span></a><nav aria-label="Navigazione principale"><a href="#catalogo">I progetti</a><a href="#raccolta">La raccolta</a><a class="github-profile" href="https://github.com/yellowelise" target="_blank" rel="noopener noreferrer">GitHub <span aria-hidden="true">⌘</span></a></nav></header>
<main><section class="hero"><div class="hero-copy"><div class="eyebrow"><span class="line"></span> MEDIAERA SRL PRESENTA</div><h1>Un’idea.<br>Un problema.<br><em>Un’app.</em></h1><p>Strumenti per imparare, creare e semplificare le cose. Le applicazioni promosse da Mediaera Srl, dal laboratorio scolastico allo smartphone.</p><a class="primary" href="#catalogo">Esplora i progetti <span class="button-count">${data.length}</span></a><div class="period">20 MAGGIO — 3 OTTOBRE 2026</div></div><div class="hero-stage"><div class="stage-label"><span>IN PRIMO PIANO</span><span>01 / ${data.length}</span></div><div class="feature-head"><span class="featured-mark">RC</span><div><h2>reCoding</h2><p>Il laboratorio, ovunque.</p></div><span class="feature-type">WEB APP</span></div><a class="screen-link" href="https://recoding.cloud/site/" target="_blank" rel="noopener noreferrer" aria-label="Scopri reCoding"><img src="assets/recoding.webp" alt="Interfaccia del desktop reCoding con applicazioni a finestre" width="1200" height="750"></a><div class="stage-bottom"><span>Desktop cloud · Coding · Scuola</span><a href="#rc">Scopri il progetto</a></div><div class="mini-apps"><a href="#vu"><span class="mini-mark">Vu</span><span>VidMeUp<small>CREATIVITÀ</small></span></a><a href="#yr"><span class="mini-mark">YR</span><span>Yalper Replay<small>SPORT</small></span></a><a href="#ai"><span class="mini-mark">Ai</span><span>AIuta<small>PRODUTTIVITÀ</small></span></a></div></div></section>
<div class="metrics" aria-label="La raccolta in numeri"><div><strong>${data.length}</strong><span>progetti raccolti</span></div><div><strong>7</strong><span>ambiti da esplorare</span></div><div><strong>${inventory.length}</strong><span>repository con attività nel periodo</span></div><div class="metric-note">Web, mobile e oltre.<br><b>Una curiosità, tante direzioni.</b></div></div>
<section class="catalogue" id="catalogo"><div class="section-head"><div><div class="eyebrow">L’ARCHIVIO DEI PROGETTI</div><h2>Trova la tua prossima app.</h2></div><span class="result-count" id="result-count" role="status" aria-live="polite">${data.length} progetti</span></div><div class="controls" hidden><div class="search-wrap"><span aria-hidden="true">⌕</span><input type="search" id="search" placeholder="Cerca un’app, un’idea, una caratteristica…" aria-label="Cerca nei progetti"><kbd aria-hidden="true">/</kbd></div><label class="sort-label">Ordina per<select id="sort"><option value="curated">In evidenza</option><option value="recent">Attività più recente</option><option value="name">Nome A–Z</option></select></label></div><div class="filters" aria-label="Filtra per ambito" hidden><button class="filter active" data-filter="Tutti" aria-pressed="true">Tutti <span>${data.length}</span></button>${categories.map(c=>`<button class="filter" data-filter="${c}" aria-pressed="false">${c} <span>${data.filter(p=>p.category===c).length}</span></button>`).join('')}</div><div class="project-grid">${cards}</div><div class="empty" hidden><h3>Nessun progetto trovato.</h3><p>Prova un’altra parola o esplora tutti gli ambiti.</p><button id="reset">Mostra tutti i progetti</button></div><noscript><p>Il catalogo completo è disponibile anche senza JavaScript. Attiva JavaScript per ricerca e filtri.</p></noscript></section>
<section class="about" id="raccolta"><div><div class="eyebrow">DIETRO LA RACCOLTA</div><h2>Progetti diversi.<br>La stessa voglia<br><em>di costruire.</em></h2></div><div class="about-copy"><p>Scuola, creatività, organizzazione personale, sport. Ogni progetto esplora un modo concreto di usare il software nella vita di tutti i giorni.</p><p class="promoter"><strong>Promotrice: Mediaera Srl.</strong><br>Sviluppo dei progetti: Andrea Battellocchi.</p><details><summary>Fonti, periodo e screenshot</summary><p>Catalogo verificato il 3 ottobre 2026 tramite accesso autenticato all’account GitHub <a href="https://github.com/yellowelise">yellowelise</a>: ${inventory.length} repository originali con commit nel periodo 20 maggio–3 ottobre 2026.</p><p>Le caratteristiche sono ricavate dai README e dalla documentazione dei progetti. Le date indicano sviluppo o aggiornamento, non necessariamente il lancio o la creazione del prodotto. I repository privati richiedono un accesso autorizzato.</p><p>${screenshots.filter(x=>x.image).length} screenshot reali acquisiti il 3 ottobre 2026 dalle pagine pubbliche, incluse le schermate di accesso. I siti di presentazione delle app Android non sono schermate dell’app installata. Nessun accesso a dati personali o aree riservate.</p><p>I siti promozionali sono accorpati alle relative app; i vecchi repository senza attività nel periodo e i fork sono esclusi.</p></details><a class="text-link" href="https://github.com/yellowelise" target="_blank" rel="noopener noreferrer">Esplora il profilo GitHub</a></div></section></main><footer><a class="brand" href="#"><span class="brand-symbol">m.</span><span>Mediaera Srl<small>APP SHOWROOM · 2026</small></span></a><span>${data.length} progetti. E altre idee da costruire.</span><a href="#">Torna all’inizio</a></footer><dialog id="screenshot-dialog" aria-labelledby="screenshot-title"><div class="dialog-header"><div><h2 id="screenshot-title"></h2><p id="screenshot-caption"></p></div><button id="close-screenshot" type="button" aria-label="Chiudi screenshot">Chiudi ×</button></div><img id="screenshot-full" alt=""></dialog></body></html>`;
fs.writeFileSync(new URL('dist/index.html',import.meta.url),html);
console.log(`Generated showroom: ${data.length} projects, ${categories.length} categories.`);

